package utils

const (
    ErrUnauthorized           = "Unauthorized"
	ErrNotToken				  = "Authorization header required"
    ErrInvalidUserIDType      = "Invalid userID type"
    ErrAdminAccessRequired    = "Admin access required"
    ErrInvalidToken           = "Invalid token"
	ErrInvalidEmail			  = "Invalid email"
	ErrTokenExpired			  = "Token expired"
    ErrInvalidTokenClaims     = "Invalid token claims"
    ErrInvalidPostID          = "Invalid post id"
    ErrPostNotFound           = "Post not found"
    ErrNoPermissionPost       = "You do not have permission to edit or delete this post."
    ErrInvalidCommentID       = "Invalid comment_id"
    ErrCommentNotFound        = "Comment not found"
    ErrNoPermissionComment    = "You do not have permission to delete this comment"
    ErrInvalidPageParam       = "Invalid page parameter"
    ErrInvalidPageSizeParam   = "Invalid page_size parameter"
    ErrCouldNotFetchUsers     = "Could not fetch users"
    ErrUserNotFound           = "User not found"
    ErrOldPasswordIncorrect   = "Old password is incorrect."
    ErrInvalidUserID          = "Invalid user id"
	ErrInvalidCategoryID	  = "Invalid category id"
    ErrCouldNotFetchPosts     = "Could not fetch posts"
    ErrCouldNotFetchCategories= "Could not fetch categories"
    ErrCategoryNotFound       = "Category not found"
    ErrEndpointNotFound       = "Endpoint not found"
)

const (
    MsgRegisterSuccess        = "Register successful"
    MsgLoginSuccess           = "Login successful"
    MsgPasswordChanged        = "Password changed successfully"
    MsgUserRoleUpdated        = "User role updated"
    MsgUserDeleted            = "User deleted successfully"
    MsgUsersFetched           = "Users fetched successfully."
    MsgNoUsersFound           = "No users found."
    MsgPostCreated            = "Post created successfully"
    MsgPostUpdated            = "Post updated successfully"
    MsgPostDeleted            = "Post deleted successfully"
    MsgPostsFetched           = "Search success."
    MsgNoPostsFound           = "No matching articles found."
    MsgCategoryCreated        = "Category created successfully"
    MsgCategoryUpdated        = "Category updated successfully"
    MsgCategoryDeleted        = "Category deleted successfully"
    MsgCategoriesFetched      = "Categories fetched successfully"
    MsgCommentCreated         = "Comment created successfully"
    MsgCommentUpdated         = "Comment updated successfully"
    MsgCommentDeleted         = "Comment deleted successfully"
)

const (
	SearchSuccess    = "Search success"
	NotFoundArticles = "No matching articles found"
	UserFetchOK 	 = "Users fetched successfully"
)